### ISSUE TITLE
enum class support

### ISSUE THREAD

**Issue by JoshuaWise** [mjspncr/lzz3#28]
Firstly, I want to thank you for making `lzz`, it has saved me a lot of pain and frustration when it comes to the DRY principle.

It would be nice if enum classes (Scoped enumerations) were supported. Is there any plan to add those?

**Comment by mjspncr** [comment]
Yes, I do want to support new C++ features -- this one turned out to be quick, see #29. Just grammar and Lua change. So will need to recompile the grammar, then good to go.

**Comment by JoshuaWise** [comment]
Great, thanks!
